spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: test
    password: test!@34
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: false
    database: mysql
    show-sql: true
